### ISSUE TITLE
Error in dart run jovial_svg:svg_to_si

### ISSUE THREAD

**Issue by ashim-kr-saha** [zathras/jovial_svg#23]
Could not able to run following command

`dart run jovial_svg:svg_to_si ./assets/images/svg/logo.svg -out ./assets/images/svg`

It gives me error

`Could not find a file named "pubspec.yaml" in "/Users/username/.pub-cache/hosted/pub.dartlang.org/flutter_lints-2.0.1".`

**Comment by ashim-kr-saha** [comment]
Yes I tried that but does not work.

The error stack is looks like below
```
#0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
#1      new Package.load (package:pub/src/package.dart:128:29)
#2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:250:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:301:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:66:29)
#13     main (file:///opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by zathras** [comment]
Well...  Just to be sure, I checked `~/.pub-cache/hosted/pub.dartlang.org/flutter_lints-2.0.1` on my system, and there is a `pubspec.yaml` there.  It looks like your dart cache got corrupted somehow; nothing to do with `jovial_svg`.

Maybe try deleting it, and re-creating it?  e.g., do
```
rm -rf ~/.pub_cache
flutter pub upgrade
```
